### ISSUE TITLE
Different results for Random Effects models for Python vs Stata

### ISSUE THREAD

**Issue by brianferrell787** [bashtage/linearmodels#555] opened 2023-09-26 15:01 UTC
Hello,

I will post code soon but I wanted to ask if you or anyone has discovered a difference in estimates between using Python and Stata for RE models? We have checked the RE model estimates using your package and compared them with RE estimates in STATA and possibly R against WALHUS, AMEMIYA, SWAR, NERLOVE, and IMLE methods.  They match none.

**Comment by bashtage** [comment] 2023-09-26 15:10
Are you sure you are not doing something incorrectly?  LM is directly tested against stata and produces the same results (at with the same as Stata 13, but RE is so old, unlikely to change).

**Comment by brianferrell787** [comment] 2023-09-26 15:27
Here are results from Python, STATA, and from a page in a Econ book:
STATA
![image](https://github.com/bashtage/linearmodels/assets/58923369/116a4bee-f20c-48e1-8110-bf3bff38129e)

Copy of page 21 of Badi Baltagi's text Econometric Analysis of Panel Data  showing the results of different RE specifications.
![image](https://github.com/bashtage/linearmodels/assets/58923369/3bddf588-90f0-40f4-bd6b-1a1248164dbf)

Python
![image](https://github.com/bashtage/linearmodels/assets/58923369/d04b4bc8-ef7f-4182-bd05-a275c4b813a6)
![image](https://github.com/bashtage/linearmodels/assets/58923369/94032e99-f379-4c2c-b30e-cffc37b14b9c)

**Comment by bashtage** [comment] 2023-09-26 16:05
What if you include a constant in your model?

**Comment by bashtage** [comment] 2023-09-26 16:22
If you copy the file here https://www.wiley.com/legacy/wileychi/baltagi/supp/Gasoline.dat to the clipboard, and then run:

```python
import pandas as pd
df = pd.read_clipboard()
df2 = df.set_index(["COUNTRY","YEAR"])
df2["CONST"]=1
y=df2.LGASPCAR
x = df2[["CONST","LINCOMEP", 'LRPMG', 'LCARPCAP']]

res = lm.RandomEffects(y,x).fit()
print(res)
```


```plaintext
                       RandomEffects Estimation Summary
================================================================================
Dep. Variable:               LGASPCAR   R-squared:                        0.8293
Estimator:              RandomEffects   R-squared (Between):              0.7099
No. Observations:                 342   R-squared (Within):               0.8363
Date:                Tue, Sep 26 2023   R-squared (Overall):              0.7309
Time:                        17:19:27   Log-likelihood                    320.02
Cov. Estimator:            Unadjusted
                                        F-statistic:                      547.40
Entities:                          18   P-value                           0.0000
Avg Obs:                       19.000   Distribution:                   F(3,338)
Min Obs:                       19.000
Max Obs:                       19.000   F-statistic (robust):             547.40
                                        P-value                           0.0000
Time periods:                      19   Distribution:                   F(3,338)
Avg Obs:                       18.000
Min Obs:                       18.000
Max Obs:                       18.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
CONST          1.9967     0.1843     10.832     0.0000      1.6341      2.3593
LINCOMEP       0.5550     0.0591     9.3861     0.0000      0.4387      0.6713
LRPMG         -0.4204     0.0400    -10.515     0.0000     -0.4990     -0.3418
LCARPCAP      -0.6068     0.0255    -23.784     0.0000     -0.6570     -0.5567
```

Constants, and any other variables, have to be explicitly added, unlike some other software. This is by design and consistent with the philosophy of Python - *explicit is better than implicit*.

**Comment by bashtage** [comment] 2023-09-26 16:22
I've closed this since the code appears to be working as expected.

**Closed by bashtage** 2023-09-26 16:22 UTC
